- hosts: servers
  remote_user: ansible
  become_method: sudo
  become: yes
  tasks:
    - name: Apt Update
      apt:
        update_cache: yes

    - name: Install SSH
      apt:
        name: openssh-server
        state: present

    - name: Install JDK
      apt:
        name: default-jre
        state: present

    - name: Set authorized key taken from file
      authorized_key:
        user: charlie
        state: present
        key: "{{ lookup('id_rsa.pub', '/home/ansible/.ssh/id_rsa.pub') }}"
          
