- hosts: servers
  remote_user: ubuntu
  become_method: sudo
  become: yes
  tasks:
    - name: Apt Update
      apt:
        update_cache: yes

    - name: Install SSH
      apt:
        name: openssh-server
        state: present

    - name: Install JDK
      apt:
        name: default-jre
        state: present
    - name: Transfer the script
      copy: src=get-docker.sh dest=/home/ubuntu mode=0777

    - name: Excute script
      command: sudo sh /home/ubuntu/get-docker.sh

    - name: Allow Permissions To Use Docker Sock
      command: sudo chmod 666 /var/run/docker.sock